apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghme-backend
  labels:
    app: loghme-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loghme-backend
  template:
    metadata:
      labels:
        app: loghme-backend
    spec:
      containers:
      - name: loghme-backend
        image: registry.gitlab.com/internet-engineering-spring99/loghme-backend:<VERSION>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "275m"
            memory: "475Mi"
          requests:
            cpu: "200m"
            memory: "300Mi"
      imagePullSecrets:
      - name: regcred